name: Export YANG Files to TXT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  export-yang-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Export YANG files to TXT
      run: |
        mkdir -p txt
        for file in YANG/*.yang; do
          filename=$(basename "$file" .yang)
          cp "$file" "txt/$filename.txt"
        done

    - name: Upload TXT files as artifact
      uses: actions/upload-artifact@v3
      with:
        name: yang-txt-files
        path: txt/
